### ISSUE TITLE
SimpleCountdown极简到计日，黑暗模式下看不清楚

### ISSUE THREAD

**Issue by cw2095** [PKM-er/Pkmer-Widget#2]
https://widget.pkmer.cn/free/SimpleCountdown
黑暗模式没有适配，暗色下看不清。
![image](https://github.com/PKM-er/Pkmer-Widget/assets/31243857/bd5706cc-7674-4ccc-827c-cbd5461df8bb)

**Comment by cumany** [comment]
已修复，增加了颜色设置。
